version: '3'

services:
  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "mydatabase"
      POSTGRES_HOST: "postgresql"
      POSTGRES_PORT: "5432"

  nodejs:
    image: node:hydrogen-slim
    command: >
      sh -c "npm run build && npm start"
    working_dir: /usr/src/app
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "mydatabase"
      POSTGRES_HOST: "postgresql"
      POSTGRES_PORT: "5432"

    volumes:
      - .:/usr/src/app
    depends_on:
      - postgresql

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nodejs

